#define or ||
#define OR ||
int checkdigit(char CONVERTED_CHECKCHARACTER){
    if(CONVERTED_CHECKCHARACTER == '0' or CONVERTED_CHECKCHARACTER == '1' or CONVERTED_CHECKCHARACTER == '2' or CONVERTED_CHECKCHARACTER == '3' or CONVERTED_CHECKCHARACTER == '4' OR CONVERTED_CHECKCHARACTER == '5' OR CONVERTED_CHECKCHARACTER == '6' OR CONVERTED_CHECKCHARACTER == '7' OR CONVERTED_CHECKCHARACTER == '8' OR CONVERTED_CHECKCHARACTER == '9'){
        return 1;
    }
    else{
        return 0;
    }
}